# Requisites

- Environment with dependencies in `conda_env.yaml`
- External dependencies to be downloaded and place in `training_data/utils/external`:
    - predict_ddG.py script from PyRosetta (https://github.com/RosettaCommons/PyRosetta.notebooks/blob/master/notebooks/additional_scripts/predict_ddG.py)
    - DSPP software executable (https://github.com/PDB-REDO/dssp/releases/download/v4.4.0/mkdssp-4.4.0-linux-x64)

In [1]:
from predict import get_cif, view_pdb, predict, view_pockets, view_pockets_pathways, Site

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/nglview/__init__.py:12: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

<br>

**Files are written by default to the `predict` folder, customize it with using a different `path=` argument in the functions below.**

<br>

# Predict

## Protein structure

Provide a PDB ID or a valid .pdb or .cif (or .cif.gz) file.

In [2]:
pdb = get_cif(
    pdb_id = "6t4k"
    # file = "6t4k.pdb"
)

view_pdb(pdb)

PDBeMolstar(bg_color='#F7F7F7', custom_data={'data': "data_6T4K\n#\n_entry.id 6T4K\n#\n_citation.abstract ?\n_…

## Predict

**ColabFold MSA**

For single predictions, HHBlits' resource-intensive calculations are substituted in this notebook by an HHM built from a Multiple Sequence Alignment computed through ColabFold. To use ColabFold's MSA services, please provide your email to the server's call below, respect [ColabFold's MSA server usage limits](https://github.com/sokrypton/ColabFold#:~:text=Is%20it%20okay%20to%20use%20the%20MMseqs2%20MSA%20server%20(cf.run_mmseqs2)%20on%20a%20local%20computer%3F) and [acknowledge the tool](https://github.com/sokrypton/ColabFold#how-do-i-reference-this-work) appropriately. Consider switching to the [local setup of HHBlits](https://github.com/frannerin/AlloPockets#hhblits-for-multiple-predictions) to perform multiple AlloPockets computations.

In [3]:
clean_pdb, predictions = predict(
    pdb,
    protein_chains=["A"],
    email="youremail@yourinstitution.com"
)

***** POCKET HUNTING BEGINS *****
***** POCKET HUNTING ENDS *****

COMPLETE: 100%|██████████████████████████████████████████████████████████████| 150/150 [elapsed: 00:02 remaining: 00:00]

  0%|          | 0/9 [00:00<?, ?it/s]

Output()

core.chemical.GlobalResidueTypeSet: Finished initializing fa_standard residue type set.  Created 985 residue types
core.chemical.GlobalResidueTypeSet: Total time to initialize 0.38255 seconds.
core.import_pose.import_pose: File 'predict/6t4k.cif' automatically determined to be of type mmCIF from contents.

2025-07-16 17:30:20,566 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2025-07-16 17:30:20,569 - .prody - WARNING - WARNING No anisotropic B factors found
2025-07-16 17:30:20,569 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.03s.
2025-07-16 17:30:20,628 - .prody - DEBUG - Hessian was built in 0.06s.
2025-07-16 17:30:21,089 - .prody - DEBUG - 714 modes were calculated in 0.46s.
2025-07-16 17:30:21,106 - .prody - INFO - Calculating stiffness matrix.
2025-07-16 17:30:21,198 - .prody - DEBUG - Stiffness matrix calculated in 0.09s.
2025-07-16 17:30:21,199 - .prody - INFO - The range of effective force constant is: 7.608823820052636 to 24.362333890274677.
2025-07-16 17:30:21,213 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:21,435 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:30:21,449 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:21,637 - .prody - DEBUG - 10 modes were calculated in 0.19s.
2025-07-16 17:30:21,642 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:21,908 - .prody - DEBUG - 10 modes were calculated in 0.26s.
2025-07-16 17:30:21,920 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:22,113 - .prody - DEBUG - 10 modes were calculated in 0.19s.
2025-07-16 17:30:22,119 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:22,122 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:22,131 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:22,141 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:30:22,147 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:22,149 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:22,159 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:22,183 - .prody - DEBUG - 10 modes were calculated in 0.02s.
2025-07-16 17:30:22,195 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:22,437 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:30:22,446 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:22,723 - .prody - DEBUG - 10 modes were calculated in 0.27s.
2025-07-16 17:30:22,732 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:22,982 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:30:22,992 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:23,239 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:30:23,250 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:23,527 - .prody - DEBUG - 10 modes were calculated in 0.26s.
2025-07-16 17:30:23,537 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:23,770 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:23,780 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:23,987 - .prody - DEBUG - 10 modes were calculated in 0.21s.
2025-07-16 17:30:23,997 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:24,119 - .prody - DEBUG - 10 modes were calculated in 0.12s.
2025-07-16 17:30:24,133 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:24,400 - .prody - DEBUG - 10 modes were calculated in 0.27s.
2025-07-16 17:30:24,409 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:24,657 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:30:24,663 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:24,927 - .prody - DEBUG - 10 modes were calculated in 0.26s.
2025-07-16 17:30:24,943 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:25,194 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:30:25,205 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:25,441 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:25,447 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,454 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:30:25,460 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,462 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,467 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,470 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,475 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,478 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,483 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,485 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,491 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,493 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,498 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,501 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,506 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,508 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,514 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,516 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,522 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,524 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,529 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,532 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,537 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,539 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,545 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,547 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,553 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,556 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,561 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,563 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,568 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,571 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,577 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,579 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,585 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,587 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,592 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,595 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,600 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,603 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,608 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,611 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,617 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,619 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,625 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,628 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,633 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,636 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,641 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,644 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,650 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,652 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,657 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,660 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,666 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,668 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,673 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,676 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,681 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,699 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:30:25,704 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,707 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,721 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,723 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,729 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,732 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,737 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,740 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,748 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:25,765 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:30:25,770 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,773 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,778 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,781 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,794 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:25,796 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,802 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,804 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,810 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,812 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,817 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,821 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,832 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,834 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,840 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,842 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,848 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,851 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,862 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:25,867 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,872 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,875 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,881 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,883 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:25,889 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:25,896 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:30:25,909 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:26,154 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:30:26,171 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:26,408 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:26,419 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:26,650 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:26,658 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:26,900 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:30:26,909 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:26,993 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2025-07-16 17:30:27,006 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:27,238 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:27,252 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:27,480 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:27,489 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:27,724 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:27,737 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:27,981 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:30:27,991 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:28,205 - .prody - DEBUG - 10 modes were calculated in 0.21s.
2025-07-16 17:30:28,214 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:28,421 - .prody - DEBUG - 10 modes were calculated in 0.21s.
2025-07-16 17:30:28,431 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:28,681 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:30:28,687 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:28,725 - .prody - DEBUG - 10 modes were calculated in 0.04s.
2025-07-16 17:30:28,732 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:28,935 - .prody - DEBUG - 10 modes were calculated in 0.20s.
2025-07-16 17:30:28,945 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:29,166 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:30:29,172 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:29,416 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:30:29,431 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:29,667 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:30:29,676 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:29,732 - .prody - DEBUG - 10 modes were calculated in 0.05s.
2025-07-16 17:30:29,745 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:29,765 - .prody - DEBUG - 10 modes were calculated in 0.02s.
2025-07-16 17:30:29,771 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:29,774 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:29,784 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:30,008 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:30:30,020 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:30,254 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:30,260 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:30,266 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:30:30,271 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:30,274 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:30,279 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:30,282 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:30,294 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:30,502 - .prody - DEBUG - 10 modes were calculated in 0.21s.
2025-07-16 17:30:30,512 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:30,698 - .prody - DEBUG - 10 modes were calculated in 0.18s.
2025-07-16 17:30:30,711 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:30,938 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:30,948 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:31,171 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:30:31,177 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:31,418 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:30:31,428 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:31,645 - .prody - DEBUG - 10 modes were calculated in 0.21s.
2025-07-16 17:30:31,656 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:31,702 - .prody - DEBUG - 10 modes were calculated in 0.04s.
2025-07-16 17:30:31,707 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:31,710 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:31,715 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:31,718 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:31,724 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:31,726 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:31,735 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:31,941 - .prody - DEBUG - 10 modes were calculated in 0.20s.
2025-07-16 17:30:31,950 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:31,959 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:31,964 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:31,970 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:30:31,976 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:32,212 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:30:32,221 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:32,444 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:30:32,458 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:32,694 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:32,706 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:32,909 - .prody - DEBUG - 10 modes were calculated in 0.20s.
2025-07-16 17:30:32,915 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:33,149 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:33,161 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:33,407 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:30:33,417 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:33,450 - .prody - DEBUG - 10 modes were calculated in 0.03s.
2025-07-16 17:30:33,456 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:33,458 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:33,464 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:33,467 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:30:33,472 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:33,715 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:30:33,724 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:33,946 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:30:33,952 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:33,965 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:30:33,973 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:34,193 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:30:34,203 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:34,427 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:30:34,436 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:30:34,667 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:34,679 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:34,892 - .prody - DEBUG - 10 modes were calculated in 0.21s.
2025-07-16 17:30:34,901 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:35,141 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:35,151 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:35,360 - .prody - DEBUG - 10 modes were calculated in 0.21s.
2025-07-16 17:30:35,381 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:35,612 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:30:35,623 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:30:35,654 - .prody - DEBUG - 10 modes were calculated in 0.03s.
2025-07-16 17:30:35,660 - .prody - DEBUG - Kirchhoff was built in 0.00s.

In [4]:
predictions

          Allosteric score
pocket2           0.849939
pocket1           0.601982
pocket5           0.002779
pocket7           0.000518
pocket9           0.000358
pocket4           0.000327
pocket3           0.000321
pocket6           0.000170
pocket10          0.000143
pocket8           0.000135

## View

In [5]:
view_pockets(
    clean_pdb,
    pockets={"pocket2": {"color": "green"}, "pocket1": {"color": "blue"}}, # {"pocketn": {"color": ""}}
)

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…

### Optional: view allosteric network pathways

**View the allosteric pathways originating from the predicted pocket towards spatially distant residues in the structure.**

The allosteric network can be chosen between [correlationplus](https://github.com/tekpinar/correlationplus) (Dynamical Cross-Correlation from Elastic Network Models) or ProDy's [Perturbation Response Scanning](http://www.bahargroup.org/prody/prs/). The shortest paths between residues of the source pocket and other spatially distant residues (given a distance threshold) are calculated using [NetworkX](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.weighted.multi_source_dijkstra.html) with Dijkstra’s algorithm.

In [6]:
view_pockets_pathways(
    clean_pdb, 
    pathways="correlationplus", # or 'prs'
    source_pocket="pocket2", # Source pocket to calculate paths to/from
    pathway_dist_threshold=20, # Minimum distance between residues to calculate paths from
    n_top_pathways=10, # Number of pathways to view in the structure
    pockets={"pocket2": {"color": "green"}}, # {"pocketn": {"color": ""}} # Same dictionary of pockets as above to visualize pockets alongside paths
)

2025-07-16 17:31:05,599 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2025-07-16 17:31:05,602 - .prody - WARNING - WARNING No anisotropic B factors found
2025-07-16 17:31:05,603 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.03s.
2025-07-16 17:31:05,671 - .prody - DEBUG - Hessian was built in 0.06s.
2025-07-16 17:31:06,331 - .prody - DEBUG - 100 modes were calculated in 0.66s.

Pathway #1 (blue): A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370, A:ALA:371
Pathway #2 (cyan): A:MET:358, A:VAL:361, A:VAL:363, A:LEU:407, A:LEU:410
Pathway #3 (green): A:MET:358, A:VAL:361, A:ARG:364, A:CYS:366, A:SER:408, A:HIS:411
Pathway #4 (yellow): A:MET:358, A:VAL:360, A:SER:413, A:ILE:417, A:THR:421
Pathway #5 (red): A:LYS:354, A:ALA:449
Pathway #6 (purple): A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370, A:ASN:373
Pathway #7 (grey): A:MET:358, A:VAL:360, A:LEU:419, A:THR:421, A:PHE:450, A:HIS:451
Pathway #8 (light blue): A:LEU:293, A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:ALA:368
Pathway #9 (light cyan): A:LYS:354, A:LEU:448, A:ALA:449
Pathway #10 (mint green): A:ARG:296, A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…

### Optional: view a target site

Set an object of the `Site` class passing a modulator molecule (and defining the site around it) or a list of residues. Then visualize it in the structure to assess overlap with predicted pockets (residues of the site will be colored green in the protein cartoon visualization).

<br>

#### With a modulator molecule

In [7]:
# Desired modulator is label_asym_id 'C'
pdb.residues.query("label_asym_id == 'C'")

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
2061,4F1,C,3,.,?,602,4F1,A,1,602,?,?,?,?

In [8]:
site = Site(
    pdb, 
    modulator_residues=pdb.residues.query("label_asym_id == 'C'")
)
site

In [9]:
view_pockets_pathways(
    clean_pdb, 
    pathways="correlationplus",
    source_pocket="pocket2", 
    pockets={"pocket2": {"color": "green"}}, # {"pocketn": {"color": ""}} 
    site_residues=site.residues,
    modulator_residues=site.modulator_residues,
)

2025-07-16 17:31:06,748 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2025-07-16 17:31:06,751 - .prody - WARNING - WARNING No anisotropic B factors found
2025-07-16 17:31:06,751 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.03s.

Pathway #1 (blue): A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370, A:ALA:371
Pathway #2 (cyan): A:MET:358, A:VAL:361, A:VAL:363, A:LEU:407, A:LEU:410
Pathway #3 (green): A:MET:358, A:VAL:361, A:ARG:364, A:CYS:366, A:SER:408, A:HIS:411
Pathway #4 (yellow): A:MET:358, A:VAL:360, A:SER:413, A:ILE:417, A:THR:421
Pathway #5 (red): A:LYS:354, A:ALA:449
Pathway #6 (purple): A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370, A:ASN:373
Pathway #7 (grey): A:MET:358, A:VAL:360, A:LEU:419, A:THR:421, A:PHE:450, A:HIS:451
Pathway #8 (light blue): A:LEU:293, A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:ALA:368
Pathway #9 (light cyan): A:LYS:354, A:LEU:448, A:ALA:449
Pathway #10 (mint green): A:ARG:296, A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…

#### With a list of residues

In [10]:
# List of residue numbers of site
resnums = site.residues.label_seq_id.to_list()
resnums

['73',
 '77',
 '78',
 '80',
 '81',
 '84',
 '85',
 '88',
 '109',
 '110',
 '111',
 '112',
 '113',
 '114',
 '232',
 '235',
 '236',
 '238',
 '239',
 '240',
 '241',
 '243',
 '248',
 '250',
 '251',
 '252',
 '253',
 '254',
 '255',
 '257',
 '258',
 '261',
 '262']

In [11]:
# Site can be defined with a list of residues instead of a modulator
res_site = Site(
    pdb=pdb,
    residues=[{"label_asym_id": "A", "label_seq_id": seqnum} for seqnum in resnums]
)
res_site.residues

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,TRP,A,1,73,?,317,TRP,A,1,73,UNP,P51449,317,W
1,ALA,A,1,77,?,321,ALA,A,1,77,UNP,P51449,321,A
2,HIS,A,1,78,?,322,HIS,A,1,78,UNP,P51449,322,H
3,LEU,A,1,80,?,324,LEU,A,1,80,UNP,P51449,324,L
4,THR,A,1,81,?,325,THR,A,1,81,UNP,P51449,325,T
5,ILE,A,1,84,?,328,ILE,A,1,84,UNP,P51449,328,I
6,GLN,A,1,85,?,329,GLN,A,1,85,UNP,P51449,329,Q
7,VAL,A,1,88,?,332,VAL,A,1,88,UNP,P51449,332,V
8,LEU,A,1,109,?,353,LEU,A,1,109,UNP,P51449,353,L
9,LYS,A,1,110,?,354,LYS,A,1,110,UNP,P51449,354,K
10,ALA,A,1,111,?,355,ALA,A,1,111,UNP,P51449,355,A
11,GLY,A,1,112,?,356,GLY,A,1,112,UNP,P51449,356,G
12,ALA,A,1,113,?,357,ALA,A,1,113,UNP,P51449,357,A
13,MET,A,1,114,?,358,MET,A,1,114,UNP,P51449,358,M
14,CYS,A,1,232,?,476,CYS,A,1,232,UNP,P51449,476,C
15,HIS,A,1,235,?,479,HIS,A,1,235,UNP,P51449,479,H
16,VAL,A,1,236,?,480,VAL,A,1,236,UNP,P51449,480,V
17,ARG,A,1,238,?,482,ARG,A,1,238,UNP,P51449,482,R
18,LEU,A,1,239,?,483,LEU,A,1,239,UNP,P51449,483,L
19,GLN,A,1,240,?,484,GLN,A,1,240,UNP,P51449,484,Q
20,ILE,A,1,241,?,485,ILE,A,1,241,UNP,P51449,485,I
21,GLN,A,1,243,?,487,GLN,A,1,243,UNP,P51449,487,Q
22,ILE,A,1,248,?,492,ILE,A,1,248,UNP,P51449,492,I
23,VAL,A,1,250,?,494,VAL,A,1,250,UNP,P51449,494,V
24,GLN,A,1,251,?,495,GLN,A,1,251,UNP,P51449,495,Q
25,ALA,A,1,252,?,496,ALA,A,1,252,UNP,P51449,496,A
26,ALA,A,1,253,?,497,ALA,A,1,253,UNP,P51449,497,A
27,PHE,A,1,254,?,498,PHE,A,1,254,UNP,P51449,498,F
28,PRO,A,1,255,?,499,PRO,A,1,255,UNP,P51449,499,P
29,LEU,A,1,257,?,501,LEU,A,1,257,UNP,P51449,501,L
30,TYR,A,1,258,?,502,TYR,A,1,258,UNP,P51449,502,Y
31,LEU,A,1,261,?,505,LEU,A,1,261,UNP,P51449,505,L
32,PHE,A,1,262,?,506,PHE,A,1,262,UNP,P51449,506,F

In [12]:
view_pockets_pathways(
    clean_pdb, 
    pathways="correlationplus",
    source_pocket="pocket2", 
    pockets={"pocket2": {"color": "green"}}, # {"pocketn": {"color": ""}} 
    site_residues=site.residues,
)

2025-07-16 17:31:07,119 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2025-07-16 17:31:07,119 - .prody - WARNING - WARNING No anisotropic B factors found
2025-07-16 17:31:07,120 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.02s.

Pathway #1 (blue): A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370, A:ALA:371
Pathway #2 (cyan): A:MET:358, A:VAL:361, A:VAL:363, A:LEU:407, A:LEU:410
Pathway #3 (green): A:MET:358, A:VAL:361, A:ARG:364, A:CYS:366, A:SER:408, A:HIS:411
Pathway #4 (yellow): A:MET:358, A:VAL:360, A:SER:413, A:ILE:417, A:THR:421
Pathway #5 (red): A:LYS:354, A:ALA:449
Pathway #6 (purple): A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370, A:ASN:373
Pathway #7 (grey): A:MET:358, A:VAL:360, A:LEU:419, A:THR:421, A:PHE:450, A:HIS:451
Pathway #8 (light blue): A:LEU:293, A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:ALA:368
Pathway #9 (light cyan): A:LYS:354, A:LEU:448, A:ALA:449
Pathway #10 (mint green): A:ARG:296, A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…